# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: "prometheus"
#     static_configs:
#       - targets: ["localhost:9090"]

#   - job_name: "my-nextjs-app"
#     metrics_path: /metrics
#     static_configs:
#       - targets: ["34.77.70.99:80"]


global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "my-nextjs-app"
    metrics_path: /app/api/metrics
    static_configs:
      - targets: ["34.8.138.57:80"]
